### ISSUE TITLE
Mousing over a custom-rendered day

### ISSUE THREAD

**Issue by cabintech** [year-calendar/js-year-calendar#11] opened 2019-07-19 20:42 UTC
I have implemented a custom renderer that behaves just like "background" style with some improvements. But when the mouse passes over my rendered days the gray-block highlight does not appear, nor is my renderer called. So how can I get the mouse-over highlighting to work when there is a custom renderer?

Here is my render code:

	        style: "custom", //"background",
	        customDataSourceRenderer: function(ele, renderDate, eventList) {
	        	// Similar to "background" style plus
	        	// - Draw black angled line on shared days so 2 adjacent events of the same color can be distinguised
	        	// - Highlight today
	        	$(ele).css("border-radius", "0px");
        		let c0 = eventList[0].color;
        		let c1 = eventList[0].color;
        		let cline = eventList[0].color;
        		let count = eventList.length;
        		
        		if (eventList[0].startDate.getTime() == renderDate.getTime()) {
        			// Beginning of an event
        			if (count == 2) {
        				// Two events on this date, must be end of one and start of another
        				c0 = eventList[1].color;
        				cline = "black";
        			}
        			else {
        				c0 = "white";
        			}
        		}
        		else if (eventList[0].endDate.getTime() == renderDate.getTime()) {
        			// End of an event
        			if (count == 2) {
        				// Two events on this date, must be end of one and start of another
        				c1 = eventList[1].color;
        				cline = "black";
        			}
        			else {
        				c1 = "white";
        			}
        		}
        		
        		$(ele).css("background", "linear-gradient(-45deg, "+c1+", "+c1+" 48%, "+cline+" 49%, "+cline+" 50%, "+c0+" 51%, "+c0+")");
        		
        		// Highlight today with an inset border (so DIV size does not change)
        		if (today.getTime() == renderDate.getTime()) {
        			$(ele).css("box-shadow", "inset 0px 0px 0px 2px red");
        		}
	        },

**Comment by cabintech** [comment] 2019-07-22 02:00
Update: It is possible to get the custom rendered day to highlight as the mouse passes over using the `mosueOnDay `and `mouseOutDay `events:

	mouseOnDay: function(e) {
		if (e.events.length > 0) { 
			$(e.element).children(":first").css("box-shadow", "inset 0px 0px 0px 2px black");
		}
	},
	mouseOutDay: function(e) {
		if (e.events.length > 0) { 
			$(e.element).children(":first").css("box-shadow", "none");
		}
	},

However, swiping over custom rendered days still does not show any highlighting and there appears to be no way to make it work - my code gets no mouse on/out events and there is no selection event until the user releases the mouse to complete the swipe. The selection itself works fine, but there is no way to visually show the swipe over custom rendered days. Seems the API is not sufficient to properly represent swipe activity - seems there needs to be events generated as the swipe is in-progress.

In a more general sense, it would be nice to have control over the highlighting when the mouse moves over un-scheduled days (swiping or just hovering) - there is no way to alter the grey rectangle visual representation. Mouse On/Out events happen only on days where an event is scheduled.

**Comment by cabintech** [comment] 2019-07-22 15:10
OK, could only figure this out by examining the built in rendering code. The HTML element passed into the renderer is the child DIV of the day cell (`day-content`). Seems natural to set CSS styles on that element to draw the rendering and it appears to work properly. _But the mouse-over highlighting only works if the PARENT of this element is the one rendered_ (e.g. CSS styles must be set on the PARENT of the passed element).

Does not make a lot of sense to pass the renderer an element that should not be used for renderering. One just has to know to use the parent instead.

I will leave this issue open as a doc problem (changing this now would break existing code). The doc should be clear about what HTML element is passed to the renderer, and dependencies other code has for mouse-over behavior to work.

Issue #12 notes that the mouse-over events (mouseOnDay, mouseOutDay) pass the parent DIV and not the child content DIV, which is quite inconsistent with the render event. Again, docs should be clarified.

**Comment by cabintech** [comment] 2019-07-22 15:18
PS. For anyone wanting to implement a custom renderer, here is a fully working example:

        style: "custom", //"background",
        customDataSourceRenderer: function(ele, renderDate, eventList) {
        	// Similar to "background" style plus
        	// - Draw black angled line on shared days so 2 adjacent events of the same color can be distinguised
        	// - Highlight today
                ele = ele.parentElement; // We are passed the child of the element to be styled
        	$(ele).css("border-radius", "0px");
    		let c0 = eventList[0].color;
    		let c1 = eventList[0].color;
    		let cline = eventList[0].color;
    		let count = eventList.length;
    		
    		if (eventList[0].startDate.getTime() == renderDate.getTime()) {
    			// Beginning of an event
    			if (count == 2) {
    				// Two events on this date, must be end of one and start of another
    				c0 = eventList[1].color;
    				cline = "black";
    			}
    			else {
    				c0 = "white";
    			}
    		}
    		else if (eventList[0].endDate.getTime() == renderDate.getTime()) {
    			// End of an event
    			if (count == 2) {
    				// Two events on this date, must be end of one and start of another
    				c1 = eventList[1].color;
    				cline = "black";
    			}
    			else {
    				c1 = "white";
    			}
    		}
    		
    		$(ele).css("background", "linear-gradient(-45deg, "+c1+", "+c1+" 48%, "+cline+" 49%, "+cline+" 50%, "+c0+" 51%, "+c0+")");
    		
    		// Highlight today with an inset border (so DIV size does not change)
    		if (today.getTime() == renderDate.getTime()) {
    			$(ele).css("box-shadow", "inset 0px 0px 0px 2px red");
    		}
        },

**Comment by Paul-DS** [comment] 2019-08-13 15:52
The problem is treated in #12, so I close this issue.

**Closed by Paul-DS** 2019-08-13 15:52 UTC
